`define CT           //GS CT

`define KRED3I        //NH2/qTEASLA_OFFICIAL: 0:BASELINE 1: REVISED 2: MONTGOMERY 3: BARETT 4: GENERAL 5:KRED2I 6:KRED3I (CT)
`define PERFERMANCE          //AREA BALANCE PERFERMANCE

`define Q 12289
`define N 1024
`define WIDTH 14